---
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Download the install-agent.sh script
  get_url:
    url: https://raw.githubusercontent.com/henrygd/beszel/main/supplemental/scripts/install-agent.sh
    dest: /tmp/install-agent.sh
    mode: '0755' # Set executable permissions

- name: Remove beszel agent if service exists
  become: true
  ansible.builtin.command:
    cmd: /tmp/install-agent.sh -u
  when: ansible_facts.services['beszel-agent.service'] is defined

- name: Run the install-agent.sh script with auto-update
  shell: yes | /tmp/install-agent.sh -p {{ beszel_agent_ssh_port }} -k "{{ beszel_agent_ssh_key }}"
  when: beszel_agent_autoupdate | bool
  ignore_errors: false

- name: Run the install-agent.sh script without auto-update
  shell: yes N | /tmp/install-agent.sh -p {{ beszel_agent_ssh_port }} -k "{{ beszel_agent_ssh_key }}"
  when: not beszel_agent_autoupdate | bool
  ignore_errors: false

- name: Add firewall rule for beszel
  ansible.builtin.include_role:
    name: firewall
    tasks_from: add_rule
  vars:
    __fwrule:
      port: "{{ beszel_agent_ssh_port }}"
      rule: "allow"
