---
- name: Install required packages for WireGuard
  ansible.builtin.apt:
    name:
      - wireguard
      - wireguard-tools
      - net-tools
      #- iptables
      #- iptables-persistent
      #- netfilter-persistent
    state: present
    update_cache: yes
  become: true

- name: Enable IPv4 forwarding
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes
  become: true

- name: Generate WireGuard private key
  ansible.builtin.command: wg genkey
  register: wg_private_key
  changed_when: false
  become: true

- name: Create WireGuard configuration with peers
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: "/etc/wireguard/{{ wireguard_interface }}.conf"
    owner: root
    group: root
    mode: '0600'
  vars:
    private_key: "{{ wg_private_key.stdout }}"
  become: true

- name: Open WireGuard-Port
  ansible.builtin.import_role:
    name: firewall
    tasks_from: add_rule
  vars:
    fwrule:
      port: "{{ wireguard_port }}"
      rule: allow
      proto: udp

- name: System cleanup
  ansible.builtin.apt:
    autoremove: yes
    autoclean: yes
  become: true
