-
  name: Install required packages for WireGuard
  ansible.builtin.apt:
    name:
      - wireguard
      - wireguard-tools
      - net-tools
    state: present
    update_cache: yes
  become: true

- name: Import key generation tasks
  import_tasks: __create/gen_key.yml

- name: Enable IPv4 forwarding
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes
  become: true

- name: Slurp private key
  ansible.builtin.slurp:
    path: /etc/wireguard/privatekey{{ wireguard_interface }}
  register: private_key_content
  become: true

- set_fact:
    private_key: "{{ private_key_content['content'] | b64decode | replace('\n', '') }}"
  no_log: true

- name: Create WireGuard configuration with peers
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: "/etc/wireguard/{{ wireguard_interface }}.conf"
    owner: root
    group: root
    mode: '0600'
  become: true

- name: Open WireGuard-Port
  ansible.builtin.import_role:
    name: firewall
    tasks_from: add_rule
  vars:
    fwrule:
      port: "{{ wireguard_port }}"
      rule: allow
      proto: udp

- name: System cleanup
  ansible.builtin.apt:
    autoremove: yes
    autoclean: yes
  become: true