---
- name: Enable PubkeyAuthentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#Pubkey'
    line: 'PubkeyAuthentication yes'
  become: true
  notify: Restart sshd

- name: Disable PasswordAuthentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication'
    line: 'PasswordAuthentication no'
  become: true
  notify: Restart sshd
