---
- name: Add rule for port {{ fwrule.port }}
  community.general.ufw:
    rule: "{{ fwrule.rule | default('allow') }}"
    port: "{{ fwrule.port }}"
    proto: "{{ fwrule.proto | default(omit) }}"
  become: true
  notify: Reload ufw
