users:
  - name: kreativmonkey
    comment: Personal access user
    uid: 1000
    password: "{{ lookup('community.general.bitwarden', 'ServerUser', field='password') | first }}"
    shell: /bin/bash
    group:
      name: kreativmonkey
      gid: 1000
    groups:
      - name: sudo
      - name: docker
    create_home: true
    authorized_keys:
      - https://github.com/kreativmonkey.keys
    update_password: always
  - name: ansib
    comment: User to role out ansible tasks
    uid: 1101
    password: "{{ lookup('community.general.bitwarden', 'Ansible User', field='password') | first }}"
    shell: /bin/bash
    group:
      name: ansible
      gid: 1101
    groups:
      - name: sudo
    create_home: true
    update_password: always
    authorized_keys:
      - https://github.com/kreativmonkey.keys