---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Upgrade all packages (Debian/Ubuntu)
  ansible.builtin.apt:
    name: '*'
    state: latest
    update_cache: yes
  register: update
  when: ansible_os_family == "Debian"

- name: Reboot if needed (Linux)
  reboot:
  when: ansible_os_family == "Debian" and update.changed
